version: "3.8"
services:
  app:
    image: alicehccn/fury:latest
    command: sh -c "yarn install && yarn tsc && yarn start"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fury
    volumes:
      - ./:/app
      