version: 2.1
jobs:
  install-dependencies:
    docker:
      - image: node:18-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Node Packages
          command: |
            yarn install
  build-deploy:
    docker:
      - image: circleci/python:3.6.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - install-aws-venv
      - push-docker-image

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - install-dependencies
      - build-deploy:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
            - aws-config
          requires:
            - install-dependencies

commands:
  install-aws-venv:
    description: "Install AWS in venv"
    steps:
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli>=2.7.9

  push-docker-image:
      description: "Push Docker Image"
      steps:
        - run:
            name: Docker Login
            command: |
              . venv/bin/activate
              docker login --username AWS -p $(aws ecr get-login-password --region us-west-2) ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com
        - run:
            name: Docker Build
            command: |
              docker build -f ./Dockerfile -t fury .
        - run:
            name: Docker Tag
            command: |
              docker tag fury:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/thrive
        - run:
            name: Docker Push
            command: |
              docker push fury:latest

