version: 2.1
jobs:
  install-dependencies:
    docker:
      - image: node:18-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Node Packages
          command: |
            yarn install
  build-deploy:
    docker:
      - image: circleci/python:3.6.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - build-deploy

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - install-dependencies
      - build-deploy:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
            - aws-config
          requires:
            - install-dependencies

commands:
  build-deploy:
      description: "Build Docker Image"
      steps:
        - run:
            name: Docker Login
            command: |
              docker login --username $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        - run:
            name: Docker Build
            command: |
              docker build . -t alicehccn/fury:latest
        - run:
            name: Docker Push
            command: |
              docker push alicehccn/fury:latest
